export const MONTSERRAT_FONTS = {
  'Montserrat-Black': require('../../assets/fonts/montserrat/Montserrat-Black.ttf'),
  'Montserrat-BlackItalic': require('../../assets/fonts/montserrat/Montserrat-BlackItalic.ttf'),
  'Montserrat-Bold': require('../../assets/fonts/montserrat/Montserrat-Bold.ttf'),
  'Montserrat-BoldItalic': require('../../assets/fonts/montserrat/Montserrat-BoldItalic.ttf'),
  'Montserrat-ExtraBold': require('../../assets/fonts/montserrat/Montserrat-ExtraBold.ttf'),
  'Montserrat-ExtraBoldItalic': require('../../assets/fonts/montserrat/Montserrat-ExtraBoldItalic.ttf'),
  'Montserrat-ExtraLight': require('../../assets/fonts/montserrat/Montserrat-ExtraLight.ttf'),
  'Montserrat-ExtraLightItalic': require('../../assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf'),
  'Montserrat-Italic': require('../../assets/fonts/montserrat/Montserrat-Italic.ttf'),
  'Montserrat-Light': require('../../assets/fonts/montserrat/Montserrat-Light.ttf'),
  'Montserrat-LightItalic': require('../../assets/fonts/montserrat/Montserrat-LightItalic.ttf'),
  'Montserrat-Medium': require('../../assets/fonts/montserrat/Montserrat-Medium.ttf'),
  'Montserrat-MediumItalic': require('../../assets/fonts/montserrat/Montserrat-MediumItalic.ttf'),
  'Montserrat-Regular': require('../../assets/fonts/montserrat/Montserrat-Regular.ttf'),
  'Montserrat-SemiBold': require('../../assets/fonts/montserrat/Montserrat-SemiBold.ttf'),
  'Montserrat-SemiBoldItalic': require('../../assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf'),
  'Montserrat-Thin': require('../../assets/fonts/montserrat/Montserrat-Thin.ttf'),
  'Montserrat-ThinItalic': require('../../assets/fonts/montserrat/Montserrat-ThinItalic.ttf'),
};
